compile_pdf:
  image: hsteinshiromoto/tex
  script:
    - cd src/latex && xelatex main.tex \
                && biber main \
                #&& makeindex main.idx \
                && xelatex main.tex
                #&& makeindex main.nlo -s nomencl.ist -o main.nls \
        
  artifacts:
    paths:
      - src/latex/main.pdf
