compile_pdf:
  image: aergus/latex
  script:
    - cd latex && xelatex main.tex \
               && makeindex main.idx \
               && makeindex main.nlo -s nomencl.ist -o main.nls \
               && biber main \
               && xelatex main.tex
  artifacts:
    paths:
      - main.pdf
